name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env

      - name: Build Docker image
        run: docker build -t senthilindia17/nextjs-fullstack .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Publish Docker image to Docker Hub
        run: docker push senthilindia17/nextjs-fullstack:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker image from Docker Hub
        run: docker pull senthilindia17/nextjs-fullstack:latest

      - name: Stop and Remove Old Container
        run: |
          docker ps -q --filter "name=nextjs-fullstack-container" | xargs -r docker stop
          docker ps -aq --filter "name=nextjs-fullstack-container" | xargs -r docker rm

      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 --name nextjs-fullstack-container \
          --env-file .env \
          senthilindia17/nextjs-fullstack:latest
